# Generated by Django 4.2.6 on 2023-12-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('8', '8'), ('5', '5'), ('3', '3')], default='Free', max_length=30),
        ),
    ]
