# Generated by Django 4.2.6 on 2023-12-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('5', '5'), ('8', '8'), ('3', '3')], default='Free', max_length=30),
        ),
    ]
