# Generated by Django 5.0.1 on 2024-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_number_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='number_of_votes',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('8', '8')], default='Free', max_length=30),
        ),
    ]
